/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
*Thai Bao Trung
*12
*/
package views.PhatThuongManagerFrame;

import controllers.PhatThuongManagerController.DanhHieuController;
import controllers.PhatThuongManagerController.PTCuoiNamController;
import controllers.PhatThuongManagerController.PhanQuaController;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.DanhHieuModel;
import models.PhanQuaModel;
import models.PhatThuongCuoiNamModel;
import services.MysqlConnection;
import models.quaModel;
import controllers.PhatThuongManagerController.addQuaController;

/**
 *
 * @author TNTDT
 */
public class PTDacBietJFrame extends javax.swing.JFrame {

    private JFrame parentJFrame;
    DefaultTableModel tableModel;

    /**
     * Creates new form PTCuoiNamJFrame
     */
    public PTDacBietJFrame(JFrame parentJFrame) {
        initComponents();
        this.parentJFrame = parentJFrame;
        parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJFrame.setEnabled(true);
                close();
            }

        });
        tableModel = (DefaultTableModel) tblHsNhanThuong.getModel();
        tblHsNhanThuong.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        tblHsNhanThuong.setRowHeight(40);
        tblHsNhanThuong.validate();
        tblHsNhanThuong.repaint();
        tblHsNhanThuong.setFont(new Font("Arial", Font.PLAIN, 14));
        tblHsNhanThuong.getColumnModel().getColumn(0).setMaxWidth(40);
        tblHsNhanThuong.getColumnModel().getColumn(0).setMinWidth(40);
        tblHsNhanThuong.getColumnModel().getColumn(0).setPreferredWidth(80);

        showHSNhanThuong();
        initComboBox();
    }
    private void initComboBox(){
         Connection conn = null;
        Statement stm = null;
        try{
             conn = MysqlConnection.getMysqlConnection();
             String sql = "select tenphanthuong from phan_thuong ";
             PreparedStatement pstmt = conn.prepareStatement(sql);
              ResultSet rs = pstmt.executeQuery();
              boxqua.removeAllItems();
              while(rs.next()){
                  boxqua.addItem(rs.getString("tenphanthuong"));
              }
        }
        catch(Exception e){
             e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    

    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    public void showHSNhanThuong() {

        Connection conn = null;
        Statement stm = null;

         try{
           
                conn = MysqlConnection.getMysqlConnection();
            String sql = "select ID, hoTen, ROUND(Datediff(CURDATE(), namSinh)/365,0) as tuoi from nhan_khau where ROUND(Datediff(CURDATE(), namSinh)/365,0) <= 18";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tableModel.setRowCount(0);
            while(rs.next()){
                tableModel.addRow(new Object[]{
                    rs.getInt("ID"),
                rs.getString("hoTen"),
                rs.getString("tuoi"),
            });
            }
            tableModel.fireTableDataChanged();
            }
         catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidnhankhau = new javax.swing.JTextField();
        txttuoi = new javax.swing.JTextField();
        btnPhatThuong = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHsNhanThuong = new javax.swing.JTable();
        boxqua = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phát Thưởng Cuối Năm");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách học sinh nhận thưởng dịp đặc biệt");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 312, 436, 30));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 619, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Phát thưởng cho học sinh");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 12, 323, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID nhân khẩu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 50, 93, 24));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tuổi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 140, 81, 25));

        txtidnhankhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtidnhankhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnhankhauActionPerformed(evt);
            }
        });
        jPanel1.add(txtidnhankhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 50, 310, -1));

        txttuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txttuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 139, 310, -1));

        btnPhatThuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhatThuong.setText("Phát Thưởng");
        btnPhatThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhatThuongActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhatThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 136, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Chọn Quà:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 103, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Họ và tên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 97, 80, 21));

        txthoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 94, 310, -1));

        tblHsNhanThuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID nhân khẩu", "Họ và Tên", "Tuổi"
            }
        ));
        tblHsNhanThuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHsNhanThuongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHsNhanThuong);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, 239));

        boxqua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(boxqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidnhankhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnhankhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnhankhauActionPerformed

    private void btnPhatThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhatThuongActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        Statement stm = null;
        try {
            conn = MysqlConnection.getMysqlConnection();
        } catch (SQLException ex) {
            Logger.getLogger(PTDacBietJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PTDacBietJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
             try{
            quaModel q = new quaModel();
            q.setId(Integer.parseInt(txtidnhankhau.getText()));
            q.setHoTen(txthoten.getText());
            q.setTuoi(Integer.parseInt(txttuoi.getText()));
            q.setTenqua(boxqua.getSelectedItem().toString());
            addQuaController dao = new addQuaController();
            dao.insert(q);
           
            JOptionPane.showMessageDialog(this, "Lưu thành công");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPhatThuongActionPerformed

    private void tblHsNhanThuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHsNhanThuongMouseClicked
        // TODO add your handling code here:
         int row = tblHsNhanThuong.getSelectedRow();
        String id = tblHsNhanThuong.getValueAt(row, 0).toString();
        String hoTen = tblHsNhanThuong.getValueAt(row, 1).toString();
        String tuoi = tblHsNhanThuong.getValueAt(row, 2).toString();
        
        txtidnhankhau.setText(id);
        txthoten.setText(hoTen);
        txttuoi.setText(tuoi);
    }//GEN-LAST:event_tblHsNhanThuongMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxqua;
    private javax.swing.JButton btnPhatThuong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHsNhanThuong;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtidnhankhau;
    private javax.swing.JTextField txttuoi;
    // End of variables declaration//GEN-END:variables
}
