/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.PhatThuongManagerFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.MysqlConnection;

/**
 *
 * @author oOOo
 */
public class thongkequa extends javax.swing.JFrame {
     private DefaultTableModel tblModel;
     private DefaultTableModel tblModel1;
     private JFrame parentJFrame;
    /**
     * Creates new form thongkequa
     */
    public thongkequa(JFrame parentJFrame) {
        initComponents();
        initTableModel();
        initTableModel1();
         this.parentJFrame = parentJFrame;
         parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJFrame.setEnabled(true);
                close();
            }
        });
    }
    
    
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    
    private void initTableModel(){
        String[] columnNames = new String[]{"ID Gia đình", "Số phần thưởng", "Số tiền"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tblqua.setModel(tblModel);
    }
    private void initTableModel1(){
        String[] columnNames = new String[]{"Tổng số phần thưởng", "Tổng số tiền"};
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(columnNames);
        tbltongket.setModel(tblModel1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblqua = new javax.swing.JTable();
        btnthongke = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltongket = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID gia đình", "Số quà", "Số tiền quà"
            }
        ));
        jScrollPane1.setViewportView(tblqua);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 204));

        btnthongke.setText("Thống kê");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });
        getContentPane().add(btnthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 393, -1, -1));

        tbltongket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tổng số quà", "Tổng số tiền"
            }
        ));
        jScrollPane2.setViewportView(tbltongket);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 347, 170, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement stm = null;

        try{
            conn = MysqlConnection.getMysqlConnection();
           
            String sql = "select idHoKhau, count(tenphanthuong1) as sophanthuong, count(tenphanthuong1)*10000 as sotienqua from nhan_khau n, thanh_vien_cua_ho t, phatqua p where t.idNhanKhau = n.id and n.hoTen = p.hoTen group by idHoKhau";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("idHoKhau"),
                rs.getInt("sophanthuong"),
                rs.getInt("sotienqua"),
            });
            }
            tblModel.fireTableDataChanged();
            
            
            
            String sql1 = "select count(tenphanthuong1) as sophanthuong, count(tenphanthuong1)*10000 as sotien from nhan_khau n, thanh_vien_cua_ho t, phatqua p, phan_thuong pt where t.idNhanKhau = n.id and n.hoTen = p.hoTen";
            PreparedStatement pstmt1 = conn.prepareStatement(sql1);
            ResultSet rs1 = pstmt1.executeQuery();
            tblModel1.setRowCount(0);
            while(rs1.next()){
                tblModel1.addRow(new Object[]{
                rs1.getInt("sophanthuong"),
                rs1.getInt("sotien"),
            });
            }
            tblModel1.fireTableDataChanged();
            }
         catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }    
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnthongke;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblqua;
    private javax.swing.JTable tbltongket;
    // End of variables declaration//GEN-END:variables
}
